# Generated by Django 5.0.13 on 2025-06-10 07:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề bài viết')),
                ('slug', models.SlugField(blank=True, help_text='Đường dẫn URL thân thiện. Để trống để tự động tạo.', max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, help_text='Hình ảnh cho bài viết (kích thước đề xuất: 800x450px)', null=True, upload_to='blog_images/', verbose_name='Hình ảnh đại diện')),
                ('excerpt', models.TextField(blank=True, help_text='Một đoạn tóm tắt ngắn gọn về bài viết (hiển thị trên trang danh sách)', verbose_name='Tóm tắt ngắn')),
                ('content', models.TextField(verbose_name='Nội dung bài viết')),
                ('author', models.CharField(default='LAMYNOVA', max_length=100, verbose_name='Tác giả')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày xuất bản')),
                ('is_published', models.BooleanField(default=True, verbose_name='Hiển thị trên trang web')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bài viết / Tin tức',
                'verbose_name_plural': 'Bài viết / Tin tức',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='Câu hỏi')),
                ('answer', models.TextField(verbose_name='Câu trả lời')),
                ('order', models.IntegerField(default=0, help_text='Số nhỏ hơn sẽ hiển thị trước', verbose_name='Thứ tự hiển thị')),
                ('is_published', models.BooleanField(default=True, verbose_name='Hiển thị trên trang web')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Câu hỏi thường gặp',
                'verbose_name_plural': 'Câu hỏi thường gặp',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
