# Generated by Django 5.0.13 on 2025-06-10 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cactrang', '0002_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
