# Generated by Django 5.0.13 on 2025-06-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tên dịch vụ')),
                ('slug', models.SlugField(blank=True, help_text='Đường dẫn URL thân thiện. Để trống để tự động tạo.', max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, help_text='Hình ảnh cho trang chi tiết dịch vụ', null=True, upload_to='service_images/', verbose_name='Hình ảnh đại diện')),
                ('brief_description', models.TextField(blank=True, help_text='Mô tả tóm tắt hiển thị trên trang danh sách dịch vụ', verbose_name='Mô tả ngắn')),
                ('full_description', models.TextField(help_text='Nội dung chi tiết của dịch vụ (có thể bao gồm HTML)', verbose_name='Mô tả đầy đủ')),
                ('features', models.TextField(blank=True, help_text='Mỗi điểm nổi bật trên một dòng hoặc định dạng HTML/Markdown (ví dụ: <li>...</li>)', verbose_name='Các điểm nổi bật')),
                ('order', models.IntegerField(default=0, help_text='Dịch vụ có số thứ tự nhỏ hơn sẽ hiển thị trước', verbose_name='Thứ tự hiển thị')),
                ('is_published', models.BooleanField(default=True, verbose_name='Hiển thị trên trang web')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dịch vụ',
                'verbose_name_plural': 'Dịch vụ',
                'ordering': ['order', 'title'],
            },
        ),
    ]
