# Generated by Django 5.0.13 on 2025-06-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Họ và tên')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Số điện thoại')),
                ('message', models.TextField(verbose_name='Nội dung tin nhắn')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian gửi')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Đã xử lý')),
                ('admin_response', models.TextField(blank=True, null=True, verbose_name='Phản hồi của Admin')),
            ],
            options={
                'verbose_name': 'Phản hồi',
                'verbose_name_plural': 'Phản hồi Khách hàng',
                'ordering': ['-created_at'],
            },
        ),
    ]
